### ISSUE TITLE
Unknown compact UTI

### ISSUE THREAD

**Issue by meltforce** [haukesomm/apple-photos-export#2]
Hi, 

freshly installed apple-photos-export from brew on Mac Mini M1 running Mac OS 15.1 and Photos 10.0

I tried to export from my long existing photo library and got the error: "Unknown compact UTI: 0%"

Then I started from scratch, created a new photo library and completely downloaded again from iClound ("Download Originals to this Mac" activated).

Tried again and got the error "Unknown compact UTI: 25%". 

Any idea?

Thanks,
Linus

**Comment by haukesomm** [comment]
Hey there!

Unfortunately, I was unable to reproduce your issue with my current set of testing libraries. If you could provide me some more information that would be greatly appreciated.

- First of all: Could you share a minimal photos library containing some demo assets that cause the export to fail? This way I can try to have a closer look myself
- What are your iCloud-related settings? There are multiple types of libraries based on the iCloud settings in the Photos app's preferences:
  1) Offline (iCloud not enabled, this is probably not what you're using based on your description)
  2) iCloud enabled with optimized storage
  3) iCloud enabled keeping all originals on your Mac
- Is the export working for some files or does it fail altogether?

Kind reagrds
Hauke
